name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          path: main

      - name: Checkout dev branch
        uses: actions/checkout@v4
        with:
          ref: dev
          path: dev

      - name: Create output folder
        run: mkdir out

      - name: Copy main site to root
        run: |
          rsync -av --exclude '.git' main/ ./out/

      - name: Copy dev site to /dev
        run: |
          mkdir -p ./out/dev
          rsync -av --exclude '.git' dev/ ./out/dev/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
          # Keep this enabled as a fallback just in case
          keep_files: true